name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
         docker build -t elaheabs/docker-react -f Dockerfile.dev .
         docker run -e CI=true elaheabs/docker-react npm run test
      

  
